version: "3.8"
services:
  app:
    build:
      dockerfile: Dockerfile
    restart: on-failure
    image: codefoodapp
    env_file: ./.env
    container_name: codefoodapp
    ports:
      - "8080:3030"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DBNAME}?useSSL=false",
        "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver",
        "spring.datasource.username" : "${MYSQL_USER}",
        "spring.datasource.password" : "${MYSQL_PASSWORD}",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update",
        "jwt_secret": "codefood"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db: