version: "3.8"
services:
  app:
    build:
      dockerfile: Dockerfile
      args:
        - MYSQL_HOST=${MYSQL_HOST:-host.docker.internal}
        - MYSQL_PORT=${MYSQL_PORT:-3306}
        - MYSQL_USER=${MYSQL_DBNAME:-codefood}
        - MYSQL_PASSWORD=${MYSQL_USER:-root}
        - MYSQL_DBNAME=${MYSQL_PASSWORD:-1234}
    restart: on-failure
    image: codefoodapp
    env_file: ./.env
    container_name: codefoodapp
    ports:
      - "8080:3030"
    environment:
      - MYSQL_HOST=${MYSQL_HOST:-host.docker.internal}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - MYSQL_USER=${MYSQL_DBNAME:-codefood}
      - MYSQL_PASSWORD=${MYSQL_USER:-root}
      - MYSQL_DBNAME=${MYSQL_PASSWORD:-1234}
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db: